重要说明：
运行ij.bat进行ij，进行命令交互
首次建立新库，并使用hrxc用户名：connect 'jdbc:derby://localhost:1527/auctiondb;user=hrxc;create=true';
建立连接：connect 'jdbc:derby://localhost:1527/auctiondb;user=hrxc';
服务启动后，如果通过网络无法联通derby数据库，则需要将start...Server.bat与stop...Server.bat中localhost修改为物理实际IP地址，然后再启动；

CREATE TABLE HRXC.BARGAIN_RECORD  ( 
    PK_ID             	VARCHAR(32) NOT NULL,
    PADDLE_NO         	VARCHAR(20) NOT NULL,
    GOODS_NO          	VARCHAR(20) NOT NULL,
    BARGAIN_CONFIRM_NO	VARCHAR(32) NOT NULL,
    HAMMER_PRICE      	INTEGER DEFAULT 0,
    COMMISSION        	INTEGER DEFAULT 0,
    OTHER_FUND        	INTEGER DEFAULT 0,
    BARGAIN_PRICE     	INTEGER DEFAULT 0,
    ACCOUNT_PAID      	INTEGER DEFAULT 0,
    NON_PAYMENT       	INTEGER DEFAULT 0,
    PROJECT_NO        	VARCHAR(20) NOT NULL,
    CONSTRAINT PK_BARGAIN_RECORD PRIMARY KEY(PK_ID)
);
CREATE UNIQUE INDEX HRXC.IDX_BARGAIN_RECORD_PG
    ON HRXC.BARGAIN_RECORD(PROJECT_NO, GOODS_NO);
CREATE TABLE HRXC.BIDDING_PADDLE  ( 
    PK_ID       	VARCHAR(32) NOT NULL,
    PADDLE_NO   	VARCHAR(20) NOT NULL,
    CUST_NAME   	VARCHAR(32) NOT NULL,
    CERT_TYPE   	VARCHAR(20),
    CERT_NO     	VARCHAR(32),
    CUST_TEL    	VARCHAR(32),
    CUST_ADDR   	VARCHAR(128),
    CASH_DEPOSIT	INTEGER NOT NULL,
    REMARKS     	VARCHAR(128),
    PROJECT_NO  	VARCHAR(20) NOT NULL,
    CONSTRAINT PK_BIDDING_PADDLE PRIMARY KEY(PK_ID)
);
CREATE UNIQUE INDEX HRXC.IDX_BIDDING_PADDLE_PP
    ON HRXC.BIDDING_PADDLE(PROJECT_NO, PADDLE_NO);
CREATE TABLE HRXC.CLIENT_SIDE  ( 
    PK_ID      	VARCHAR(32) NOT NULL,
    CLIENT_NO  	VARCHAR(20) NOT NULL,
    CLIENT_NAME	VARCHAR(64) NOT NULL,
    CONSTRAINT PK_CLIENT_SIDE PRIMARY KEY(PK_ID)
);
ALTER TABLE HRXC.CLIENT_SIDE
    ADD CONSTRAINT UN_CS_CLIENT_NO
	 UNIQUE (CLIENT_NO) ;
CREATE TABLE HRXC.GOODS_LIST  ( 
    PK_ID         	VARCHAR(32) NOT NULL,
    GOODS_NO      	VARCHAR(20) NOT NULL,
    GOODS_NAME    	VARCHAR(128) NOT NULL,
    GOODS_INTACT  	VARCHAR(128) NOT NULL,
    GOODS_SIZE    	VARCHAR(64) NOT NULL,
    CERTIFICATE_NO	VARCHAR(32),
    KEEP_PRICE    	INTEGER DEFAULT 0,
    MARKET_PRICE  	INTEGER DEFAULT 0,
    ONSET_PRICE   	INTEGER DEFAULT 0,
    PROJECT_NO    	VARCHAR(20) NOT NULL,
    CLIENT_NO     	VARCHAR(20) NOT NULL,
    CONSTRAINT PK_GOODS_LIST PRIMARY KEY(PK_ID)
);
CREATE UNIQUE INDEX HRXC.IDX_GOODS_LIST_PG
    ON HRXC.GOODS_LIST(PROJECT_NO, GOODS_NO);
CREATE TABLE HRXC.PROJECT_INFO  ( 
    PK_ID        	VARCHAR(32) NOT NULL,
    PROJECT_NO   	VARCHAR(20) NOT NULL,
    PROJECT_NAME 	VARCHAR(64) NOT NULL,
    PROJECT_STATE	VARCHAR(10) NOT NULL,
    CONSTRAINT PK_PROJECT_INFO PRIMARY KEY(PK_ID)
);
ALTER TABLE HRXC.PROJECT_INFO
    ADD CONSTRAINT UN_PI_PROJECT_NO
	 UNIQUE (PROJECT_NO) ;
CREATE TABLE HRXC.USER_INFO  ( 
    PK_ID    	VARCHAR(32) NOT NULL,
    USER_NO  	VARCHAR(20) NOT NULL,
    USER_NAME	VARCHAR(20) NOT NULL,
    PASSWORD 	VARCHAR(64) NOT NULL,
    CONSTRAINT PK_USER_INFO PRIMARY KEY(PK_ID)
);
ALTER TABLE HRXC.USER_INFO
    ADD CONSTRAINT UN_UI_USER_NO
	 UNIQUE (USER_NO) ;

