package mybatis.model.hrxc;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HRXC.USER_INFO.PK_ID
     *
     * @mbggenerated Fri Aug 16 08:56:35 CST 2013
     */
    private String PK_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HRXC.USER_INFO.USER_NO
     *
     * @mbggenerated Fri Aug 16 08:56:35 CST 2013
     */
    private String USER_NO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HRXC.USER_INFO.USER_NAME
     *
     * @mbggenerated Fri Aug 16 08:56:35 CST 2013
     */
    private String USER_NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HRXC.USER_INFO.PASSWORD
     *
     * @mbggenerated Fri Aug 16 08:56:35 CST 2013
     */
    private String PASSWORD;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HRXC.USER_INFO.PK_ID
     *
     * @return the value of HRXC.USER_INFO.PK_ID
     *
     * @mbggenerated Fri Aug 16 08:56:35 CST 2013
     */
    public String getPK_ID() {
        return PK_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HRXC.USER_INFO.PK_ID
     *
     * @param PK_ID the value for HRXC.USER_INFO.PK_ID
     *
     * @mbggenerated Fri Aug 16 08:56:35 CST 2013
     */
    public void setPK_ID(String PK_ID) {
        this.PK_ID = PK_ID == null ? null : PK_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HRXC.USER_INFO.USER_NO
     *
     * @return the value of HRXC.USER_INFO.USER_NO
     *
     * @mbggenerated Fri Aug 16 08:56:35 CST 2013
     */
    public String getUSER_NO() {
        return USER_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HRXC.USER_INFO.USER_NO
     *
     * @param USER_NO the value for HRXC.USER_INFO.USER_NO
     *
     * @mbggenerated Fri Aug 16 08:56:35 CST 2013
     */
    public void setUSER_NO(String USER_NO) {
        this.USER_NO = USER_NO == null ? null : USER_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HRXC.USER_INFO.USER_NAME
     *
     * @return the value of HRXC.USER_INFO.USER_NAME
     *
     * @mbggenerated Fri Aug 16 08:56:35 CST 2013
     */
    public String getUSER_NAME() {
        return USER_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HRXC.USER_INFO.USER_NAME
     *
     * @param USER_NAME the value for HRXC.USER_INFO.USER_NAME
     *
     * @mbggenerated Fri Aug 16 08:56:35 CST 2013
     */
    public void setUSER_NAME(String USER_NAME) {
        this.USER_NAME = USER_NAME == null ? null : USER_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HRXC.USER_INFO.PASSWORD
     *
     * @return the value of HRXC.USER_INFO.PASSWORD
     *
     * @mbggenerated Fri Aug 16 08:56:35 CST 2013
     */
    public String getPASSWORD() {
        return PASSWORD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HRXC.USER_INFO.PASSWORD
     *
     * @param PASSWORD the value for HRXC.USER_INFO.PASSWORD
     *
     * @mbggenerated Fri Aug 16 08:56:35 CST 2013
     */
    public void setPASSWORD(String PASSWORD) {
        this.PASSWORD = PASSWORD == null ? null : PASSWORD.trim();
    }
}