package com.hrxc.auction.ui;

import com.hrxc.auction.action.BargainRecordAction;
import com.hrxc.auction.action.BargainRecordTableConfig;
import com.hrxc.auction.action.BaseTableModel;
import com.hrxc.auction.domain.BargainRecord;
import com.hrxc.auction.util.DictEnum;
import com.hrxc.auction.util.ExcelHelper;
import com.hrxc.auction.util.UITools;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import org.apache.commons.lang3.StringUtils;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;

/**
 *
 * @author user
 */
public class BargainRecordSettlePanel extends javax.swing.JPanel {

    /**
     * Creates new form BargainRecordSettlePanel
     */
    public BargainRecordSettlePanel(String projectNo) {
        this.projectNo = projectNo;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        fd_paddleNo_n = new org.jdesktop.swingx.JXTextField();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        searchBton_n = new org.jdesktop.swingx.JXButton();
        toSettleBton_n = new org.jdesktop.swingx.JXButton();
        exortBton_n = new org.jdesktop.swingx.JXButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        BargainRecordTableConfig.MyTableModel model_n = new BargainRecordTableConfig().new MyTableModel();

        //初始化显示数据
        Object[][] datas_n = null;
        model_n.refreshContents(datas_n);
        dataTable_n = new org.jdesktop.swingx.JXTable(model_n);
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        fd_paddleNo_y = new org.jdesktop.swingx.JXTextField();
        searchBton_y = new org.jdesktop.swingx.JXButton();
        undoSettleBton_y = new org.jdesktop.swingx.JXButton();
        exortBton_y = new org.jdesktop.swingx.JXButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        BargainRecordTableConfig.MyTableModel model_y = new BargainRecordTableConfig().new MyTableModel();

        //初始化显示数据
        Object[][] datas_y = BargainRecordAction.getAllTableData(this.getProjectNo(),DictEnum.IsSettled.HAVE_SETTLED,null, null);
        model_y.refreshContents(datas_y);
        dataTable_y = new org.jdesktop.swingx.JXTable(model_y);
        settleListPrintBton = new org.jdesktop.swingx.JXButton();
        jXLabel5 = new org.jdesktop.swingx.JXLabel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jXLabel4 = new org.jdesktop.swingx.JXLabel();
        fd_paddleNo_x = new org.jdesktop.swingx.JXTextField();
        searchBton_x = new org.jdesktop.swingx.JXButton();
        jXLabel6 = new org.jdesktop.swingx.JXLabel();

        setPreferredSize(new java.awt.Dimension(702, 443));

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(702, 443));

        jXLabel1.setText("竞买号牌：");
        jXLabel1.setBounds(0, 10, 60, 30);
        jLayeredPane1.add(jXLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fd_paddleNo_n.setBounds(60, 10, 110, 30);
        jLayeredPane1.add(fd_paddleNo_n, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jXLabel2.setForeground(new java.awt.Color(250, 12, 12));
        jXLabel2.setText("*");
        jXLabel2.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jXLabel2.setBounds(170, 10, 20, 30);
        jLayeredPane1.add(jXLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        searchBton_n.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        searchBton_n.setText("查询");
        searchBton_n.setToolTipText("");
        searchBton_n.setFocusable(false);
        searchBton_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBton_nActionPerformed(evt);
            }
        });
        searchBton_n.setBounds(190, 10, 95, 30);
        jLayeredPane1.add(searchBton_n, javax.swing.JLayeredPane.DEFAULT_LAYER);

        toSettleBton_n.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finish.png"))); // NOI18N
        toSettleBton_n.setText("款项结算");
        toSettleBton_n.setToolTipText("修改");
        toSettleBton_n.setFocusable(false);
        toSettleBton_n.setPreferredSize(new java.awt.Dimension(40, 40));
        toSettleBton_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toSettleBton_nActionPerformed(evt);
            }
        });
        toSettleBton_n.setBounds(60, 50, 120, 40);
        jLayeredPane1.add(toSettleBton_n, javax.swing.JLayeredPane.DEFAULT_LAYER);

        exortBton_n.setIcon(new javax.swing.ImageIcon(getClass().getResource("/export.png"))); // NOI18N
        exortBton_n.setToolTipText("导出");
        exortBton_n.setFocusable(false);
        exortBton_n.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exortBton_n.setPreferredSize(new java.awt.Dimension(40, 40));
        exortBton_n.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        exortBton_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exortBton_nActionPerformed(evt);
            }
        });
        exortBton_n.setBounds(10, 50, 40, 40);
        jLayeredPane1.add(exortBton_n, javax.swing.JLayeredPane.DEFAULT_LAYER);

        //隐藏第一列（主键）
        UITools.hideColumn(dataTable_n, 1);
        jScrollPane1.setViewportView(dataTable_n);

        jScrollPane1.setBounds(0, 94, 850, 400);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("未结算", jLayeredPane1);

        jXLabel3.setText("竞买号牌：");
        jXLabel3.setBounds(0, 10, 60, 30);
        jLayeredPane2.add(jXLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fd_paddleNo_y.setBounds(60, 10, 110, 30);
        jLayeredPane2.add(fd_paddleNo_y, javax.swing.JLayeredPane.DEFAULT_LAYER);

        searchBton_y.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        searchBton_y.setText("查询");
        searchBton_y.setToolTipText("");
        searchBton_y.setFocusable(false);
        searchBton_y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBton_yActionPerformed(evt);
            }
        });
        searchBton_y.setBounds(190, 10, 95, 30);
        jLayeredPane2.add(searchBton_y, javax.swing.JLayeredPane.DEFAULT_LAYER);

        undoSettleBton_y.setIcon(new javax.swing.ImageIcon(getClass().getResource("/undo.png"))); // NOI18N
        undoSettleBton_y.setText("撤销结算");
        undoSettleBton_y.setToolTipText("修改");
        undoSettleBton_y.setFocusable(false);
        undoSettleBton_y.setPreferredSize(new java.awt.Dimension(40, 40));
        undoSettleBton_y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoSettleBton_yActionPerformed(evt);
            }
        });
        undoSettleBton_y.setBounds(60, 50, 120, 40);
        jLayeredPane2.add(undoSettleBton_y, javax.swing.JLayeredPane.DEFAULT_LAYER);

        exortBton_y.setIcon(new javax.swing.ImageIcon(getClass().getResource("/export.png"))); // NOI18N
        exortBton_y.setToolTipText("导出");
        exortBton_y.setFocusable(false);
        exortBton_y.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exortBton_y.setPreferredSize(new java.awt.Dimension(40, 40));
        exortBton_y.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        exortBton_y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exortBton_yActionPerformed(evt);
            }
        });
        exortBton_y.setBounds(10, 50, 40, 40);
        jLayeredPane2.add(exortBton_y, javax.swing.JLayeredPane.DEFAULT_LAYER);

        //隐藏第一列（主键）
        UITools.hideColumn(dataTable_y, 1);
        jScrollPane2.setViewportView(dataTable_y);

        jScrollPane2.setBounds(0, 94, 850, 400);
        jLayeredPane2.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        settleListPrintBton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/print.png"))); // NOI18N
        settleListPrintBton.setText("结款单打印");
        settleListPrintBton.setFocusable(false);
        settleListPrintBton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settleListPrintBtonActionPerformed(evt);
            }
        });
        settleListPrintBton.setBounds(190, 50, 131, 41);
        jLayeredPane2.add(settleListPrintBton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jXLabel5.setForeground(new java.awt.Color(250, 12, 12));
        jXLabel5.setText("*");
        jXLabel5.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jXLabel5.setBounds(170, 10, 20, 30);
        jLayeredPane2.add(jXLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("已结算", jLayeredPane2);

        jXLabel4.setText("竞买号牌：");
        jXLabel4.setBounds(0, 10, 60, 30);
        jLayeredPane3.add(jXLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fd_paddleNo_x.setBounds(60, 10, 110, 30);
        jLayeredPane3.add(fd_paddleNo_x, javax.swing.JLayeredPane.DEFAULT_LAYER);

        searchBton_x.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        searchBton_x.setText("查询");
        searchBton_x.setToolTipText("");
        searchBton_x.setFocusable(false);
        searchBton_x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBton_xActionPerformed(evt);
            }
        });
        searchBton_x.setBounds(190, 10, 95, 30);
        jLayeredPane3.add(searchBton_x, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jXLabel6.setForeground(new java.awt.Color(250, 12, 12));
        jXLabel6.setText("*");
        jXLabel6.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jXLabel6.setBounds(170, 10, 20, 30);
        jLayeredPane3.add(jXLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("退还保证金", jLayeredPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchBton_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBton_nActionPerformed
        String paddleNo = fd_paddleNo_n.getText().trim();
        if (StringUtils.isEmpty(paddleNo)) {
            JOptionPane.showMessageDialog(this.getRootPane(), "请输入竞买号牌后再进行查询！");
            return;
        }
        refreshTableDatas(DictEnum.IsSettled.NO_SETTLED, paddleNo, null);
    }//GEN-LAST:event_searchBton_nActionPerformed

    private void toSettleBton_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toSettleBton_nActionPerformed
        if (UITools.getCheckedRows(dataTable_n) != 1) {
            JOptionPane.showMessageDialog(this.getRootPane(), "请确认您选择了一条记录！");
        } else {
            ArrayList<String> list = UITools.getCheckedRowsId(dataTable_n);
            String pkId = list.get(0);
            BargainRecord dto = BargainRecordAction.getObjectById(pkId);
            BargainRecordEditDialog dialog = new BargainRecordEditDialog((javax.swing.JFrame) this.getRootPane().getParent(), true, dto, this);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_toSettleBton_nActionPerformed

    private void exortBton_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exortBton_nActionPerformed
        HSSFWorkbook wb = ExcelHelper.createExcel((BaseTableModel) dataTable_n.getModel());
        UITools.exportExcel(this.getRootPane(), wb);
    }//GEN-LAST:event_exortBton_nActionPerformed

    private void searchBton_yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBton_yActionPerformed
        String paddleNo = fd_paddleNo_y.getText().trim();
        if (StringUtils.isEmpty(paddleNo)) {
            JOptionPane.showMessageDialog(this.getRootPane(), "请输入竞买号牌后再进行查询！");
            return;
        }
        refreshTableDatas(DictEnum.IsSettled.HAVE_SETTLED, paddleNo, null);
    }//GEN-LAST:event_searchBton_yActionPerformed

    private void undoSettleBton_yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoSettleBton_yActionPerformed
        if (UITools.getCheckedRows(dataTable_y) != 1) {
            JOptionPane.showMessageDialog(this.getRootPane(), "请确认您选择了一条记录！");
        } else {
            ArrayList<String> list = UITools.getCheckedRowsId(dataTable_y);
            String pkId = list.get(0);
            BargainRecord dto = BargainRecordAction.getObjectById(pkId);
            BargainRecordEditDialog dialog = new BargainRecordEditDialog((javax.swing.JFrame) this.getRootPane().getParent(), true, dto, this);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_undoSettleBton_yActionPerformed

    private void exortBton_yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exortBton_yActionPerformed
        HSSFWorkbook wb = ExcelHelper.createExcel((BaseTableModel) dataTable_y.getModel());
        UITools.exportExcel(this.getRootPane(), wb);
    }//GEN-LAST:event_exortBton_yActionPerformed

    private void settleListPrintBtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settleListPrintBtonActionPerformed
//        if (UITools.getCheckedRows(dataTable) != 1) {
//            JOptionPane.showMessageDialog(this.getRootPane(), "请确认您选择了一条记录！");
//        } else {
//            ArrayList<String> list = UITools.getCheckedRowsId(dataTable);
//            String pkId = list.get(0);
//            BiddingRecordPrintDialog dialog = new BiddingRecordPrintDialog((javax.swing.JFrame) this.getRootPane().getParent(), true, pkId, Constant.PrintType.TYPE_SETTLE_LIST_PRINT);
//            dialog.setLocationRelativeTo(this);
//            dialog.setVisible(true);
//        }
    }//GEN-LAST:event_settleListPrintBtonActionPerformed

    private void searchBton_xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBton_xActionPerformed
        String paddleNo = fd_paddleNo_x.getText().trim();
        if (StringUtils.isEmpty(paddleNo)) {
            JOptionPane.showMessageDialog(this.getRootPane(), "请输入竞买号牌后再进行查询！");
            return;
        }
        //TODO:查询出竞买号牌信息
    }//GEN-LAST:event_searchBton_xActionPerformed

    /**
     * 刷新表单数据
     */
    public void refreshTableDatas(String isSettled, String paddleNo, String goodsNo) {
        BargainRecordTableConfig.MyTableModel model = (BargainRecordTableConfig.MyTableModel) dataTable_n.getModel();
        model.refreshContents(BargainRecordAction.getAllTableData(this.getProjectNo(), isSettled, paddleNo, goodsNo));
        //TODO:必须要重新设置一下model，否则刷新内容后界面无变化
        dataTable_n.setModel(model);
    }

    public String getProjectNo() {
        return projectNo;
    }
    private String projectNo;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXTable dataTable_n;
    private org.jdesktop.swingx.JXTable dataTable_y;
    private org.jdesktop.swingx.JXButton exortBton_n;
    private org.jdesktop.swingx.JXButton exortBton_y;
    private org.jdesktop.swingx.JXTextField fd_paddleNo_n;
    private org.jdesktop.swingx.JXTextField fd_paddleNo_x;
    private org.jdesktop.swingx.JXTextField fd_paddleNo_y;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private org.jdesktop.swingx.JXLabel jXLabel4;
    private org.jdesktop.swingx.JXLabel jXLabel5;
    private org.jdesktop.swingx.JXLabel jXLabel6;
    private org.jdesktop.swingx.JXButton searchBton_n;
    private org.jdesktop.swingx.JXButton searchBton_x;
    private org.jdesktop.swingx.JXButton searchBton_y;
    private org.jdesktop.swingx.JXButton settleListPrintBton;
    private org.jdesktop.swingx.JXButton toSettleBton_n;
    private org.jdesktop.swingx.JXButton undoSettleBton_y;
    // End of variables declaration//GEN-END:variables
}
