package com.hrxc.auction.ui;

import com.hrxc.auction.action.BargainRecordAction;
import com.hrxc.auction.action.BiddingPaddleAction;
import com.hrxc.auction.action.PaymentListAction;
import com.hrxc.auction.domain.BiddingPaddle;
import com.hrxc.auction.domain.PaymentList;
import com.hrxc.auction.util.UITools;
import com.hrxc.auction.util.DictEnum;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author user
 */
public class BargainRecordSettleDialog extends javax.swing.JDialog {

    /**
     * Creates new form BargainRecordEditDialog
     */
    public BargainRecordSettleDialog(java.awt.Frame parent, boolean modal, BiddingPaddle paddleInfo, PaymentList paymentInfo, ArrayList<String> recordIds, JPanel listDataPanel) {
        super(parent, modal);
        this.paddleInfo = paddleInfo;
        this.paymentInfo = paymentInfo;
        this.recordIds = recordIds;
        this.listDataPanel = listDataPanel;
        initComponents();
        //获取焦点
        fd_accountPaid.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jXTitledSeparator1 = new org.jdesktop.swingx.JXTitledSeparator();
        fd_paddleNo = new org.jdesktop.swingx.JXTextField();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        fd_paymentNo = new org.jdesktop.swingx.JXTextField();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        fd_goodsNum = new org.jdesktop.swingx.JXTextField();
        jXLabel4 = new org.jdesktop.swingx.JXLabel();
        fd_totalAmount = new org.jdesktop.swingx.JXTextField();
        jXLabel5 = new org.jdesktop.swingx.JXLabel();
        jXLabel6 = new org.jdesktop.swingx.JXLabel();
        fd_accountPaid = new org.jdesktop.swingx.JXTextField();
        fd_nonPayment = new org.jdesktop.swingx.JXTextField();
        closeBt = new org.jdesktop.swingx.JXButton();
        submitBt = new org.jdesktop.swingx.JXButton();
        msgLabel = new org.jdesktop.swingx.JXLabel();
        cashDepositLabel = new org.jdesktop.swingx.JXLabel();
        cb_cashDeposit = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jXLabel1.setText("竞买号牌：");

        jXTitledSeparator1.setFont(new java.awt.Font("黑体", 0, 12)); // NOI18N
        jXTitledSeparator1.setTitle("款项结算");

        fd_paddleNo.setText(UITools.getBeanPropertyValue(paddleInfo, "paddleNo"));
        fd_paddleNo.setEditable(false);

        jXLabel2.setText("付款编号：");

        fd_paymentNo.setText(UITools.getBeanPropertyValue(paymentInfo, "paymentNo"));
        fd_paymentNo.setEditable(false);

        jXLabel3.setText("拍品数量：");

        fd_goodsNum.setText(UITools.getBeanPropertyValue(paymentInfo, "goodsNum"));
        fd_goodsNum.setEditable(false);

        jXLabel4.setText("总金额：");

        fd_totalAmount.setText(UITools.getBeanPropertyValue(paymentInfo, "totalAmount"));
        fd_totalAmount.setEditable(false);

        jXLabel5.setText("已付款：");

        jXLabel6.setText("未付款：");

        fd_accountPaid.setText(UITools.getBeanPropertyValue(paymentInfo, "accountPaid"));

        fd_nonPayment.setText(UITools.getBeanPropertyValue(paymentInfo, "nonPayment","0"));
        fd_nonPayment.setEditable(false);

        closeBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dialog-close.png"))); // NOI18N
        closeBt.setText("关闭");
        closeBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtActionPerformed(evt);
            }
        });

        submitBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dialog-ok.png"))); // NOI18N
        submitBt.setText("提交");
        submitBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtActionPerformed(evt);
            }
        });

        Integer cashDeposit = 0;
        if(paddleInfo.getCashDepositState().equals(DictEnum.CashDepositState.NOT_USE)){
            cashDeposit = paddleInfo.getCashDeposit();
        }
        String cashText = "您有【" + cashDeposit + "】元保证金可抵扣。";
        cashDepositLabel.setText(cashText);

        //如果保证金非“未使用”状态
        if(!paddleInfo.getCashDepositState().equals(DictEnum.CashDepositState.NOT_USE)){
            cb_cashDeposit.setEnabled(false);
            cb_cashDeposit.setSelected(false);
            cb_cashDeposit.setText("保证金已抵扣，无法再次使用！");
        }else{
            //默认使用状态
            cb_cashDeposit.setEnabled(true);
            cb_cashDeposit.setSelected(true);
            cb_cashDeposit.setText("保证金未抵扣，是否使用？");

            //重新计算已付款与未付款
            Integer accountPaid = paymentInfo.getTotalAmount() - paddleInfo.getCashDeposit();
            fd_accountPaid.setText(String.valueOf(accountPaid));
        }
        cb_cashDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_cashDepositActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXTitledSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(msgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(78, 78, 78)
                                    .addComponent(closeBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(submitBt, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jXLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jXLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jXLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jXLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fd_paddleNo, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fd_paymentNo, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fd_goodsNum, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fd_totalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fd_accountPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fd_nonPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(cashDepositLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cb_cashDeposit)))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jXTitledSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fd_paddleNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fd_paymentNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fd_goodsNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fd_totalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fd_accountPaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fd_nonPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashDepositLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_cashDeposit))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(closeBt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitBt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeBtActionPerformed

    private void submitBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtActionPerformed
        //进行输入项验证
        if (UITools.vilidateText(fd_accountPaid, msgLabel, true, true, false)) {
            //根据是否使用保证金计算未付款
            Integer cashDeposit = paddleInfo.getCashDeposit();
            Integer nonPayment = 0;
            //如果使用保证金
            String cashDepositState = DictEnum.CashDepositState.NOT_USE;
            if (cb_cashDeposit.isSelected()) {
                cashDepositState = DictEnum.CashDepositState.HAVE_USED;

                nonPayment = paymentInfo.getTotalAmount() - cashDeposit - Integer.parseInt(fd_accountPaid.getText());
            } else {
                cashDepositState = DictEnum.CashDepositState.NOT_USE;
                nonPayment = paymentInfo.getTotalAmount() - Integer.parseInt(fd_accountPaid.getText());
            }
            paymentInfo.setCashDepositState(cashDepositState);
            fd_nonPayment.setText(String.valueOf(nonPayment));

            //根据未付款设置付款状态
            String msg = "款项【结清】";
            if (nonPayment == 0) {
                paymentInfo.setPaymentState(DictEnum.PaymentState.HAVE_SETTLED);
            } else {
                msg = "款项【未付清】";
                paymentInfo.setPaymentState(DictEnum.PaymentState.NOT_SETTLED);
            }
            paymentInfo.setNonPayment(nonPayment);

            if (JOptionPane.showConfirmDialog(this.getRootPane(), msg + "，请确认您是否要保存数据？") == JOptionPane.YES_OPTION) {
                //插入付款记录
                PaymentListAction.saveOrUpdateObject(paymentInfo);

                //更新保证金使用状态--只有在保证金使用时更新为“已抵扣”状态
                if (paddleInfo.getCashDepositState().equals(DictEnum.CashDepositState.NOT_USE) && cashDepositState.equals(DictEnum.CashDepositState.HAVE_USED)) {
                    BiddingPaddleAction.updateCashDepositStateById(paddleInfo.getPkId(), cashDepositState, paymentInfo.getPaymentNo());
                }

                //更新成交记录结算状态
                for (int i = 0; i < recordIds.size(); i++) {
                    BargainRecordAction.updateSettleState(DictEnum.SettleState.SETTLED, recordIds.get(i), paymentInfo.getPaymentNo());
                }

                JOptionPane.showMessageDialog(this, "保存成功！");
                this.dispose();
                BargainRecordSettlePanel panel = (BargainRecordSettlePanel) this.listDataPanel;
                panel.refreshTableDatas(panel.getDataTable_s(), DictEnum.SettleState.RECHECKED, paddleInfo.getPaddleNo(), null);
            }
        }
    }//GEN-LAST:event_submitBtActionPerformed

    private void cb_cashDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_cashDepositActionPerformed
        if (!cb_cashDeposit.isSelected()) {
            Integer accountPaid = Integer.parseInt(fd_accountPaid.getText()) + paddleInfo.getCashDeposit();
            if (accountPaid <= paymentInfo.getTotalAmount()) {
                fd_accountPaid.setText(String.valueOf(accountPaid));
            }
        }
    }//GEN-LAST:event_cb_cashDepositActionPerformed
    private BiddingPaddle paddleInfo;
    private PaymentList paymentInfo;
    private ArrayList<String> recordIds;
    private JPanel listDataPanel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXLabel cashDepositLabel;
    private javax.swing.JCheckBox cb_cashDeposit;
    private org.jdesktop.swingx.JXButton closeBt;
    private org.jdesktop.swingx.JXTextField fd_accountPaid;
    private org.jdesktop.swingx.JXTextField fd_goodsNum;
    private org.jdesktop.swingx.JXTextField fd_nonPayment;
    private org.jdesktop.swingx.JXTextField fd_paddleNo;
    private org.jdesktop.swingx.JXTextField fd_paymentNo;
    private org.jdesktop.swingx.JXTextField fd_totalAmount;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private org.jdesktop.swingx.JXLabel jXLabel4;
    private org.jdesktop.swingx.JXLabel jXLabel5;
    private org.jdesktop.swingx.JXLabel jXLabel6;
    private org.jdesktop.swingx.JXTitledSeparator jXTitledSeparator1;
    private org.jdesktop.swingx.JXLabel msgLabel;
    private org.jdesktop.swingx.JXButton submitBt;
    // End of variables declaration//GEN-END:variables
}
